### ISSUE TITLE
Wikidata translation failing "No title specified for item"

### ISSUE THREAD

**Issue by mvolz** [zotero/translation-server-v2#20]
The error almost looks like a translator issue but it works in translation-server but not translation-server-v2 with the most updated version of the wikidata translator.

> curl -d '{ "query": "https://www.wikidata.org/wiki/Q33415777" }' -H 'Content-Type: application/json' http://127.0.0.1:1969/search 

>[{"key":"E4MTYBL4","version":0,"itemType":"webpage","creators":[],"tags":[],"title":"Growth of Weil-Petersson Volumes and Random Hyperbolic Surface of Large Genus","url":"https://www.wikidata.org/wiki/Q33415777","language":"en","accessDate"

(3)(+0000371): Error: No title specified for item

    Error: No title specified for item
        at Object._itemDone (/home/marielle/Code/translation-server-v2/modules/zotero/chrome/content/zotero/xpcom/translation/translate.js:682:32)
        at Object._itemDone (/home/marielle/Code/translation-server-v2/src/translation/sandboxManager.js:91:17)
        at Zotero.Item.complete (eval at <anonymous> (/home/marielle/Code/translation-server-v2/src/translation/sandboxManager.js:65:4), <anonymous>:1:306)
        at eval (eval at <anonymous> (/home/marielle/Code/translation-server-v2/src/translation/sandboxManager.js:65:4), <anonymous>:237:8)
        at /home/marielle/Code/translation-server-v2/modules/zotero/chrome/content/zotero/xpcom/utilities_translate.js:332:5
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

(2)(+0000000): Translate: Translation using Wikidata failed: 
Error: No title specified for item

Error: No title specified for item
    at Object._itemDone (/home/marielle/Code/translation-server-v2/modules/zotero/chrome/content/zotero/xpcom/translation/translate.js:682:32)
    at Object._itemDone (/home/marielle/Code/translation-server-v2/src/translation/sandboxManager.js:91:17)
    at Zotero.Item.complete (eval at <anonymous> (/home/marielle/Code/translation-server-v2/src/translation/sandboxManager.js:65:4), <anonymous>:1:306)
    at eval (eval at <anonymous> (/home/marielle/Code/translation-server-v2/src/translation/sandboxManager.js:65:4), <anonymous>:237:8)
    at /home/marielle/Code/translation-server-v2/modules/zotero/chrome/content/zotero/xpcom/utilities_translate.js:332:5
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
url => https://www.wikidata.org/wiki/Q33415777

(5)(+0000000): Translate: Running handler 0 for error

(1)(+0000000): Translation using Wikidata failed

(1)(+0000000): Error: No title specified for item

    Error: No title specified for item
        at Object._itemDone (/home/marielle/Code/translation-server-v2/modules/zotero/chrome/content/zotero/xpcom/translation/translate.js:682:32)
        at Object._itemDone (/home/marielle/Code/translation-server-v2/src/translation/sandboxManager.js:91:17)
        at Zotero.Item.complete (eval at <anonymous> (/home/marielle/Code/translation-server-v2/src/translation/sandboxManager.js:65:4), <anonymous>:1:306)
        at eval (eval at <anonymous> (/home/marielle/Code/translation-server-v2/src/translation/sandboxManager.js:65:4), <anonymous>:237:8)
        at /home/marielle/Code/translation-server-v2/modules/zotero/chrome/content/zotero/xpcom/utilities_translate.js:332:5
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

(4)(+0000000): Translate: Parsing code for Embedded Metadata (951c027d-74ac-47d4-a107-9c3069ab7b48, 2018-07-01 18:02:27)

(3)(+0000002): Translate: Beginning translation with Embedded Metadata

(3)(+0000001): Translate: Embedded Metadata: found 7 meta tags.

(3)(+0000000): Translate: Creating translate instance of type import in sandbox

(4)(+0000000): Translate: Binding sandbox to https://www.wikidata.org/wiki/Q33415777

(4)(+0000001): Translate: Parsing code for RDF (5e3ad958-ac79-463d-812b-a86a9235c28f, 2018-05-08 19:39:38)

(3)(+0000001): Translate: Initializing RDF data store

(3)(+0000005): Translate: Promise not available in sandbox in _itemDone()

(3)(+0000001): Translate: Saving item

(5)(+0000000): Translate: Running handler 0 for itemDone

(3)(+0000037): Translate: Looking for authors in byline, vcard

(3)(+0000004): Translate: Found 0 elements with 'byline' class

(3)(+0000001): Translate: Found 0 elements with 'vcard' class

(3)(+0000000): Translate: No byline found.

(3)(+0000009): Translate: Promise not available in sandbox in _itemDone()

(3)(+0000000): Translate: Saving item

(3)(+0000001): Translate: Translation successful

(5)(+0000000): Translate: Running handler 0 for done

(3)(+0000000): itemToAPIJSON: Discarded field libraryCatalog: field not valid for type webpage

**Comment by dstillman** [comment]
@adomasven: Looks like this is another XPath problem. [This line](https://github.com/zotero/translators/blob/f5b41c161f6f9da3f86456fda7fbc0e2b606a23a/Wikidata.js#L187) isn't matching anything.

**Comment by adomasven** [comment]
Closed with 77d83cce9753aed853ca4228ea3f434a756418d3

Once again, don't forget to run `npm i`, before proceeding. Deleting node_modules should not be necessary this time.
